In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('BitcoinPrice.csv')
df.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
Date     365 non-null object
Price    365 non-null float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [4]:
df.drop(['Date'], 1 , inplace = True)

In [5]:
df.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [6]:
#Predicting the next 30 days 
p_days = 30
df['Predictions'] = df[['Price']].shift(-p_days)
df.head()

Price  Predictions
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [7]:
#Separate X & Y

X = np.array(df.drop(['Predictions'],1))
X = X[: len(df) - p_days]

In [8]:
X.shape

(335, 1)

In [9]:
#Creating Y as np array 

Y = np.array(df['Predictions'])
Y = Y[:-p_days]
Y.shape

(335,)

In [10]:
#Split the data 

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size= 0.2)

In [11]:
P_days_array = np.array(df.drop(['Predictions'], 1))[-p_days:]
P_days_array

array([[ 9774.2575    ],
       [ 9725.4025    ],
       [ 9500.32416667],
       [ 9533.97933333],
       [ 9539.7125    ],
       [ 9873.81166667],
       [10088.8       ],
       [10478.90166667],
       [10790.63      ],
       [10826.275     ],
       [11713.16166667],
       [11759.01916667],
       [11703.73833333],
       [11803.88833333],
       [11816.9125    ],
       [11586.1725    ],
       [11377.80416667],
       [11397.80166667],
       [11144.38916667],
       [10450.81333333],
       [ 9988.9475    ],
       [10230.73333333],
       [10292.38333333],
       [10295.1175    ],
       [10605.82583333],
       [10746.50769231],
       [10169.09416667],
       [10030.74666667],
       [10255.9775    ],
       [10158.54083333]])

In [12]:
from sklearn.ensemble import RandomForestRegressor

Rf = RandomForestRegressor(n_estimators=1000 , random_state = 1)
Rf.fit(X_train, y_train)
print("Random forest accuracy {:.2f}%".format(Rf.score(X_test,y_test)*100))

Random forest accuracy 81.64%


In [13]:
#Predictions 

Rf_predict = Rf.predict(X_test)
Rf_predict

array([ 4564.44960583,  4433.73159167, 10396.43572583,  6048.62902583,
        5673.5467475 ,  3795.72426767,  7161.67283442,  4049.59598606,
        6586.49331583,  5065.17357788,  3830.91692231, 11031.10844767,
       10047.3144825 ,  8256.37669417, 12207.04882083,  4220.70109417,
        3544.52710545,  7170.72662667, 10037.88052833,  6361.98211654,
        3498.14725167,  4017.91830038,  5428.27521929,  4068.23387429,
        6411.8545775 ,  3944.9845375 , 11184.5685475 , 10493.43815622,
        4324.9594675 ,  3963.73275917,  7187.16762667,  8483.06229833,
        3548.18054763,  8166.321215  ,  6611.5911175 , 10238.62532833,
       10051.49938083,  3965.13542917,  3618.13805333,  3964.43467083,
        5731.24326288, 11321.04268833,  3837.16870019,  6479.80470467,
        6761.5801975 ,  4084.61084667,  6432.19630167,  4063.1853275 ,
       10427.374775  ,  4686.49264994,  3969.4172809 ,  4088.16038167,
        6816.94631917, 10160.6336925 ,  3942.77211667,  8325.93948917,
      

In [14]:
y_test

array([ 6299.39916667,  6596.61833333, 10092.75166667,  3405.64333333,
        3523.96      ,  3468.305     ,  5863.52333333,  4675.1125    ,
        7914.53916667,  5042.51769231,  3888.70166667,  9725.4025    ,
       10292.38333333,  6563.62833333, 11779.45083333,  3977.45416667,
        3452.32833333,  8063.89583333,  9791.0175    ,  6621.71166667,
        5281.80916667,  4006.11583333,  4106.87166667,  3426.19      ,
        6382.66833333,  4035.855     , 10826.275     , 10851.84833333,
        3743.905     ,  5302.9575    ,  7979.575     ,  8114.9325    ,
        4980.89833333,  8646.195     ,  6535.47666667, 10746.50769231,
       10605.82583333,  3619.96416667,  5018.49833333,  3948.41166667,
        3462.04      ,  9147.005     ,  3863.33333333,  6468.63166667,
        9096.28583333,  3912.28583333,  6531.60166667,  3865.7975    ,
       10255.9775    ,  3961.49333333,  4000.335     ,  3933.95416667,
        5654.35333333, 10158.54083333,  4034.13833333,  7338.52083333,
      

In [15]:
#Model prediction for 30 days 

Rf_predict_30  = Rf.predict(P_days_array)
Rf_predict_30

array([10432.08169333, 10424.406855  , 10296.46380583, 10347.6749225 ,
       10347.6749225 , 10384.57465333, 10047.3144825 , 10265.91752917,
       10145.7025325 , 10065.95522917, 10065.21669817, 10860.052133  ,
       10065.21669817, 11219.60604767, 11219.60604767, 11232.46461083,
       11474.44049833, 11474.44049833, 11218.3000125 , 10213.23977583,
       10160.30698833, 10032.28164833, 10056.23495083, 10056.23495083,
       10050.25262583, 10129.33422417, 10041.7655575 , 10160.6336925 ,
       10056.4743075 , 10041.7655575 ])

In [16]:
#Original Values 
df.tail(30)

Price  Predictions
335   9774.257500          NaN
336   9725.402500          NaN
337   9500.324167          NaN
338   9533.979333          NaN
339   9539.712500          NaN
340   9873.811667          NaN
341  10088.800000          NaN
342  10478.901667          NaN
343  10790.630000          NaN
344  10826.275000          NaN
345  11713.161667          NaN
346  11759.019167          NaN
347  11703.738333          NaN
348  11803.888333          NaN
349  11816.912500          NaN
350  11586.172500          NaN
351  11377.804167          NaN
352  11397.801667          NaN
353  11144.389167          NaN
354  10450.813333          NaN
355   9988.947500          NaN
356  10230.733333          NaN
357  10292.383333          NaN
358  10295.117500          NaN
359  10605.825833          NaN
360  10746.507692          NaN
361  10169.094167          NaN
362  10030.746667          NaN
363  10255.977500          NaN
364  10158.540833          NaN